#ODMD GENERATED WORKFLOW, don't change unless you are sure

name: ODMD_coffee-shop-foundation-CdkGithubWFus-west-1-workspace1
on:
  workflow_dispatch:
    inputs:
      aws_credentials:
        type: string
        description: | 
          Your AWS credentials in the format:
          [workspace1_Role/Profile]
          aws_access_key_id=01234_id
          aws_secret_access_key=56689_secret
          aws_session_token=token0123456789
      message:
        type: string
        description: additional message
jobs:
  odmd_job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - uses: ondemandenv/wflact-resolvEnvars@main
        with:
          aws_credentials: ${{github.event.inputs.aws_credentials}}
          trigger_message: ${{github.event.inputs.message}}
        env:
          ODMD_buildId: coffee-shop-foundation
          ODMD_awsRegion: us-west-1
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_coffee_shop_foundation_CdkGithubWFus_west_1_workspace1'] }}
      
      - run: |
          set -ex
          cd ${{ env.ODMD_work_dir }}
          env | grep -i ^ODMD
          chmod +x ${{ env.ODMD_entry_cmd }}&&${{ env.ODMD_entry_cmd }}||echo 'continue anyway ...'
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: coffee-shop-foundation
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_coffee_shop_foundation_CdkGithubWFus_west_1_workspace1'] }}      
          
      - uses: ondemandenv/wflact-buildProduces@main
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ODMD_buildId: coffee-shop-foundation
          ODMD_SECRETS: ${{ secrets['ODMD_SECRETS_ODMD_coffee_shop_foundation_CdkGithubWFus_west_1_workspace1'] }}

#